apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: my-tiny-app
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka-external
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: kafka-internal
  selector:
    app: kafka

