apiVersion: v1
kind: Service
metadata:
  name: my-tiny-app-ui-service
  namespace: my-tiny-app
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
    nodePort: 30002  # Access via minikube IP:30002
  selector:
    app: my-tiny-app-ui

