apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: my-tiny-app
spec:
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: zookeeper
  selector:
    app: zookeeper

