apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-tiny-app-stg
data:
  NODE_ENV: "staging"
  MONGODB_URI: "mongodb://stg-mongodb:27017/my-tiny-app-stg"
  KAFKA_BROKER: "stg-kafka:9093"
  KAFKA_TOPIC: "item-events-stg"
  KAFKA_GROUP_ID: "my-tiny-app-consumer-group-stg"
  APP_API_URL: "http://stg-my-tiny-app-service:3000"
  API_URL: "http://stg-my-tiny-app-service:3000"

