apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tiny-app
  namespace: my-tiny-app-stg
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: my-tiny-app
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tiny-app-consumer
  namespace: my-tiny-app-stg
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: my-tiny-app-consumer
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tiny-app-ui
  namespace: my-tiny-app-stg
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: my-tiny-app-ui
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"

