apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-tiny-app
data:
  MONGODB_URI: "mongodb://mongodb:27017/my-tiny-app"
  KAFKA_BROKER: "kafka:9093"
  KAFKA_TOPIC: "item-events"
  KAFKA_GROUP_ID: "my-tiny-app-consumer-group"
  APP_API_URL: "http://my-tiny-app-service:3000"
  API_URL: "http://my-tiny-app-service:3000"
  NODE_ENV: "production"
  PORT_APP: "3000"
  PORT_CONSUMER: "3001"
  PORT_UI: "3002"

