apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-tiny-app-ingress
  namespace: my-tiny-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: my-tiny-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-tiny-app-ui-service
            port:
              number: 3002
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: my-tiny-app-service
            port:
              number: 3000

