apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-tiny-app-dev
data:
  NODE_ENV: "development"
  MONGODB_URI: "mongodb://dev-mongodb:27017/my-tiny-app-dev"
  KAFKA_BROKER: "dev-kafka:9093"
  KAFKA_TOPIC: "item-events-dev"
  KAFKA_GROUP_ID: "my-tiny-app-consumer-group-dev"
  APP_API_URL: "http://dev-my-tiny-app-service:3000"
  API_URL: "http://dev-my-tiny-app-service:3000"

