apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-tiny-app-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patchesStrategicMerge:
  - configmap-patch.yaml
  - namespace-patch.yaml
  - resources-patch.yaml

images:
  - name: my-tiny-app
    newTag: dev-latest
  - name: my-tiny-app-consumer
    newTag: dev-latest
  - name: my-tiny-app-ui
    newTag: dev-latest

replicas:
  - name: my-tiny-app
    count: 1
  - name: my-tiny-app-consumer
    count: 1
  - name: my-tiny-app-ui
    count: 1

