apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tiny-app
  namespace: my-tiny-app-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: my-tiny-app
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tiny-app-consumer
  namespace: my-tiny-app-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: my-tiny-app-consumer
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tiny-app-ui
  namespace: my-tiny-app-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: my-tiny-app-ui
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"

